/*
 * The plate: the quasiperiodic tiling that sits behind every page.
 *
 * Ported from coletivo, where it was written. Three parts, in order: the
 * AmmannBeenker engine, lifted unchanged; the two palettes this site mounts it
 * with; and the wiring that keeps the plate in step with the theme.
 *
 * Its only contract with the page is #plate and the data-theme attribute on
 * <html>. It does not own the theme — script.js does, and the inline stamp in
 * every page's head puts data-theme there before first paint. This file only
 * follows that attribute.
 *
 * Everything here is enhancement: with the script blocked the page keeps the
 * CSS ground gradient it has always had, which is what --bg-gradient still is.
 */

/* ---------------------------------------------------------------------------
   AmmannBeenker — a quasiperiodic tiling background that rearranges itself
   under the pointer. No dependencies.

     const bg = AmmannBeenker.mount(element, options);
     bg.setPalette('graphite');
     bg.destroy();

   Options
     edge       number   tile edge length in px (default 32, or 21 on phones)
     palette    string   'argent' | 'graphite', or an object of the same shape
     seed       number   picks which patch of the infinite tiling you land on
     influence  number   pointer radius in px (default 100)
     stir       number   rearrangements per 100px of pointer travel (default 10)
     flipMs     number   duration of one rearrangement (default 320)

   THE TILING. Generated by de Bruijn's dual-grid method: four families of
   evenly spaced parallel lines, rotated 0°, 45°, 90°, 135°. Each crossing of
   two lines becomes one tile, a rhomb whose edge vectors are the normals of
   the crossing lines. Since those normals sit 45° apart, the only tiles
   possible are squares and 45° rhombs. Offsets that sum to zero, with no
   three lines concurrent, give the Ammann-Beenker tiling: eight-fold
   symmetric, aperiodic, with the silver ratio 1+sqrt(2) as its inflation
   constant.

   THE REARRANGEMENT. Any vertex with exactly three tiles around it is a
   "simpleton": a square at 90 degrees and two rhombs at 135, filling a
   hexagon. That hexagon admits exactly two tilings, and swapping between them
   is a phason flip, the elementary rearrangement real quasicrystals make.
   Each of the three tiles slides by one edge — by the vector from the centre
   vertex to the one neighbour that tile does not touch — and the centre vertex
   lands on the far side of the hexagon. Nothing outside the hexagon moves and
   the result is another perfectly legal Ammann-Beenker tiling.

   Vertices carry exact integer coordinates in the four grid directions, and
   pixel positions are rebuilt from those on every flip. Adding the
   displacement to the float position instead doubles that vertex's rounding
   error each time it flips, and the patch tears itself apart after a few
   hundred rearrangements.
--------------------------------------------------------------------------- */
const AmmannBeenker = (function () {
  'use strict';

  const N = 4;
  const DIR = [];
  for (let j = 0; j < N; j++) DIR.push([Math.cos(Math.PI * j / N), Math.sin(Math.PI * j / N)]);

  // Line-family pairs. First four cross at 45 or 135 degrees (rhombs), last
  // two at 90 (squares). The tones below are keyed to this order.
  const PAIRS = [[0, 1], [1, 2], [2, 3], [0, 3], [0, 2], [1, 3]];
  const PAIR_OF = {};
  PAIRS.forEach((p, i) => { PAIR_OF[p[0] * 4 + p[1]] = i; });

  // The engine's built-in defaults. Nothing on this page uses them: the plate
  // is mounted with a palette object of its own (see PLATE, further down), and
  // that is the one to edit. These are kept only so the engine still stands up
  // on its own when it is lifted back out.
  const PALETTES = {
    // Tones per orientation class are kept deliberately close together. Spread
    // them further and the tiling stops reading as a tiling and starts reading
    // as a wall of isometric cubes.
    argent: {
      field: ['#e6e9ec', '#c5cbd2'],
      rhomb: ['#eaeef1', '#e4e8ec', '#dee3e8', '#d9dee3'],
      square: ['#cdd4db', '#c6ced6'],
      alpha: 0.75,
      line: [46, 60, 74, 0.19]
    },
    graphite: {
      field: ['#1a2731', '#0d151b'],
      rhomb: ['#1e2b34', '#1b2831', '#18242c', '#152029'],
      square: ['#25363f', '#2b3e49'],
      alpha: 0.85,
      line: [150, 196, 216, 0.22]
    }
  };

  const BANDS = 24;        // vertical colour bands, so the field gradient reads
  const MAX_LIVE = 12;     // concurrent rearrangements
  // A pointer radius holds only about ten flippable sites. Hold them locked
  // much longer than this and the tiling goes inert exactly where the pointer
  // is, leaving only distant sites free to take the work.
  const COOLDOWN = 300;    // ms before a vertex may flip back

  // The plate is pinned to the viewport's top-left corner, not to its centre.
  // Anchored at W/2, H/2 every vertex moves when the window resizes, so the
  // whole pattern appears to zoom; from a fixed origin a resize only reveals
  // or hides tiles at the edges and leaves the rest exactly where they were.
  const ORIGIN_X = 0, ORIGIN_Y = 0;

  // The field ramp covers a fixed run of pixels from the top for the same
  // reason: tied to H it stretches, and the tone under a given tile changes
  // as the window grows. Canvas gradients clamp past their last stop, so a
  // taller viewport gets a flat bottom rather than a rescaled ramp.
  const FIELD_SPAN = 800;

  const hex = h => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
  const mix = (a, b, t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
  const rgb = c => 'rgb(' + (c[0] + 0.5 | 0) + ',' + (c[1] + 0.5 | 0) + ',' + (c[2] + 0.5 | 0) + ')';

  function lcg(seed) {
    let s = (seed * 2654435761) % 2147483647;
    if (s <= 0) s += 2147483646;
    return () => (s = s * 16807 % 2147483647) / 2147483647;
  }

  // Offsets must sum to zero for the eight-fold tiling, and must avoid putting
  // three lines through one point, which would produce degenerate tiles.
  function offsets(seed) {
    const r = lcg(seed || 1);
    const g = [r(), r(), r(), r()].map(v => v * 0.8 - 0.4);
    const mean = (g[0] + g[1] + g[2] + g[3]) / 4;
    return g.map(v => v - mean + 1e-4);
  }

  function mount(host, opts) {
    opts = opts || {};

    const canvas = document.createElement('canvas');
    canvas.style.cssText = 'display:block;width:100%;height:100%';
    host.appendChild(canvas);
    const ctx = canvas.getContext('2d');

    const still = matchMedia('(prefers-reduced-motion: reduce)');
    const seed = opts.seed != null ? opts.seed : 7;
    const influence = opts.influence || 100;
    const flipMs = opts.flipMs || 320;
    const perPx = (opts.stir == null ? 10 : opts.stir) / 100;

    let pal, edge, W = 0, H = 0, dpr = 1, grad = null;
    let fillCss = [], ghostCss = [], lineCss = '';

    // Vertices carry exact integer grid coordinates plus a derived pixel spot.
    let nv = 0, vx = null, vy = null, vk = null, vtile = null, vcell = null;
    // A flip moves its centre vertex and nothing else. vmove marks vertices in
    // flight, vheld marks vertices some live flip is drawing against, and vcool
    // is the pause before a centre may flip back.
    let vmove = null, vheld = null, vcool = null;
    // Tiles carry four vertex ids each, in cyclic order.
    let ntile = 0, tvert = null, ttype = null, tcx = null, tcy = null, tcell = null, tbusy = null;

    let tgrid = null, vgrid = null, cell = 1, maxR = 0;

    const live = [];
    const ptr = { x: 0, y: 0, on: false, budget: 0 };
    let raf = 0, scratch = [], vscratch = [], pool = [];

    /* ---- palette -------------------------------------------------------- */

    function usePalette(p) {
      pal = typeof p === 'string' ? (PALETTES[p] || PALETTES.argent) : (p || PALETTES.argent);
      lineCss = 'rgba(' + pal.line[0] + ',' + pal.line[1] + ',' + pal.line[2] + ',' + pal.line[3] + ')';
      const f0 = hex(pal.field[0]), f1 = hex(pal.field[1]);
      fillCss = new Array(PAIRS.length * BANDS);
      ghostCss = new Array(PAIRS.length * BANDS);
      for (let t = 0; t < PAIRS.length; t++) {
        const tone = hex(t < 4 ? pal.rhomb[t] : pal.square[t - 4]);
        for (let b = 0; b < BANDS; b++) {
          // Bake the field gradient into an opaque tile colour, so tiles that
          // overlap mid-slide can never stack up and darken.
          const solid = mix(mix(f0, f1, (b + 0.5) / BANDS), tone, pal.alpha);
          fillCss[t * BANDS + b] = rgb(solid);
          ghostCss[t * BANDS + b] = rgb(mix(solid, pal.line, 0.16));
        }
      }
      makeGradient();
    }

    function makeGradient() {
      if (!W || !H || !pal) return;
      grad = ctx.createLinearGradient(0, 0, 0, FIELD_SPAN);
      grad.addColorStop(0, pal.field[0]);
      grad.addColorStop(1, pal.field[1]);
    }

    const bandOf = y => {
      const b = (y / FIELD_SPAN * BANDS) | 0;
      return b < 0 ? 0 : b >= BANDS ? BANDS - 1 : b;
    };

    /* ---- generation ----------------------------------------------------- */

    function build() {
      edge = opts.edge || (Math.min(W, H) < 640 ? 21 : 32);
      maxR = edge * 0.95;

      // Cover the viewport diagonal with margin. A grid index range of K fills
      // a radius of roughly 2K tiles.
      const reach = Math.hypot(W, H) / edge + 8;
      const K = Math.ceil(reach / 2) + 2;
      const g = offsets(seed);
      const pad = edge * 3;

      const vmap = new Map();
      const VK = [], VX = [], VY = [], TV = [], TT = [];
      const key = [0, 0, 0, 0];

      function vid() {
        const s = key[0] + ',' + key[1] + ',' + key[2] + ',' + key[3];
        let id = vmap.get(s);
        if (id === undefined) {
          id = VX.length;
          vmap.set(s, id);
          let x = 0, y = 0;
          for (let j = 0; j < N; j++) { x += key[j] * DIR[j][0]; y += key[j] * DIR[j][1]; }
          VX.push(ORIGIN_X + x * edge);
          VY.push(ORIGIN_Y - y * edge);       // screen y points down
          VK.push(key[0], key[1], key[2], key[3]);
        }
        return id;
      }

      const k = [0, 0, 0, 0];
      for (let t = 0; t < PAIRS.length; t++) {
        const r = PAIRS[t][0], s = PAIRS[t][1];
        const ax = DIR[r][0], ay = DIR[r][1], bx = DIR[s][0], by = DIR[s][1];
        const det = ax * by - ay * bx;

        for (let kr = -K; kr <= K; kr++) {
          for (let ks = -K; ks <= K; ks++) {
            // Where line kr of family r crosses line ks of family s.
            const cr = kr + g[r], cs = ks + g[s];
            const ix = (cr * by - cs * ay) / det;
            const iy = (ax * cs - bx * cr) / det;

            // Index that crossing against every family to get the dual vertex.
            let wx = 0, wy = 0;
            for (let j = 0; j < N; j++) {
              k[j] = j === r ? kr
                   : j === s ? ks
                   : Math.ceil(DIR[j][0] * ix + DIR[j][1] * iy - g[j]);
              wx += k[j] * DIR[j][0];
              wy += k[j] * DIR[j][1];
            }

            const mx = ORIGIN_X + (wx + (ax + bx) / 2) * edge;
            const my = ORIGIN_Y - (wy + (ay + by) / 2) * edge;
            if (mx < -pad || mx > W + pad || my < -pad || my > H + pad) continue;

            // Four corners, walking the two edge vectors: k, k+r, k+r+s, k+s.
            for (let j = 0; j < N; j++) key[j] = k[j];
            const c0 = vid();
            key[r]++; const c1 = vid();
            key[s]++; const c2 = vid();
            key[r]--; const c3 = vid();

            TV.push(c0, c1, c2, c3);
            TT.push(t);
          }
        }
      }

      nv = VX.length; ntile = TT.length;
      vx = Float32Array.from(VX); vy = Float32Array.from(VY);
      vk = Int16Array.from(VK);
      vcool = new Float64Array(nv);
      vmove = new Uint8Array(nv);
      vheld = new Uint8Array(nv);
      vtile = new Array(nv);
      for (let i = 0; i < nv; i++) vtile[i] = [];

      tvert = Int32Array.from(TV);
      ttype = Uint8Array.from(TT);
      tcx = new Float32Array(ntile); tcy = new Float32Array(ntile);
      tbusy = new Uint8Array(ntile);
      tcell = new Array(ntile);

      for (let i = 0; i < ntile; i++) {
        for (let q = 0; q < 4; q++) vtile[tvert[i * 4 + q]].push(i);
        recentre(i);
      }

      cell = edge * 2;
      tgrid = new Map(); vgrid = new Map();
      for (let i = 0; i < ntile; i++) { tcell[i] = null; placeTile(i); }
      vcell = new Array(nv);
      for (let i = 0; i < nv; i++) { vcell[i] = null; placeVert(i); }
    }

    function recentre(i) {
      const o = i * 4;
      tcx[i] = (vx[tvert[o]] + vx[tvert[o + 1]] + vx[tvert[o + 2]] + vx[tvert[o + 3]]) / 4;
      tcy[i] = (vy[tvert[o]] + vy[tvert[o + 1]] + vy[tvert[o + 2]] + vy[tvert[o + 3]]) / 4;
    }

    function drop(map, key, id) {
      const b = map.get(key);
      if (!b) return;
      const ix = b.indexOf(id);
      if (ix >= 0) b.splice(ix, 1);
    }
    function put(map, key, id) {
      let b = map.get(key);
      if (!b) map.set(key, b = []);
      b.push(id);
    }
    // Math.floor, not |0. Truncation rounds toward zero, so every coordinate
    // in (-cell, 0) lands in bucket 0 while query() — which floors — looks for
    // it in bucket -1. Nothing is off-screen far enough for that to show today,
    // but the plate is anchored at the top-left corner now and the strip either
    // side of zero is exactly where its tiles live.
    function placeTile(i) {
      const key = Math.floor(tcx[i] / cell) + ',' + Math.floor(tcy[i] / cell);
      if (tcell[i] === key) return;
      if (tcell[i] !== null) drop(tgrid, tcell[i], i);
      put(tgrid, key, i);
      tcell[i] = key;
    }
    function placeVert(i) {
      const key = Math.floor(vx[i] / cell) + ',' + Math.floor(vy[i] / cell);
      if (vcell[i] === key) return;
      if (vcell[i] !== null) drop(vgrid, vcell[i], i);
      put(vgrid, key, i);
      vcell[i] = key;
    }

    function query(map, x0, y0, x1, y1, slack, out) {
      out.length = 0;
      const gx0 = Math.floor((x0 - slack) / cell), gx1 = Math.floor((x1 + slack) / cell);
      const gy0 = Math.floor((y0 - slack) / cell), gy1 = Math.floor((y1 + slack) / cell);
      for (let gx = gx0; gx <= gx1; gx++) {
        for (let gy = gy0; gy <= gy1; gy++) {
          const b = map.get(gx + ',' + gy);
          if (b) for (let m = 0; m < b.length; m++) out.push(b[m]);
        }
      }
      return out;
    }

    /* ---- the flip ------------------------------------------------------- */

    function plan(v, now) {
      const ts = vtile[v];
      if (ts.length !== 3) return null;
      // v is about to move, so nothing may be in flight on it and no live flip
      // may be drawing against it.
      if (vcool[v] > now || vmove[v] || vheld[v]) return null;

      // Each tile contributes the arc it covers around v: neighbour, far
      // corner, neighbour. With consistent winding the three arcs chain into
      // the hexagon; failing to chain means v sits on the rim of the patch.
      const A = [], M = [], B = [];
      for (let i = 0; i < 3; i++) {
        if (tbusy[ts[i]]) return null;
        const o = ts[i] * 4;
        let q = 0;
        while (q < 4 && tvert[o + q] !== v) q++;
        if (q === 4) return null;
        A.push(tvert[o + (q + 1) % 4]);
        M.push(tvert[o + (q + 2) % 4]);
        B.push(tvert[o + (q + 3) % 4]);
      }
      const ord = [0];
      for (let s = 0; s < 2; s++) {
        const from = B[ord[ord.length - 1]];
        let next = -1;
        for (let i = 0; i < 3; i++) if (ord.indexOf(i) < 0 && A[i] === from) { next = i; break; }
        if (next < 0) return null;
        ord.push(next);
      }
      if (B[ord[2]] !== A[ord[0]]) return null;

      const n = [A[ord[0]], A[ord[1]], A[ord[2]]];
      const m = [M[ord[0]], M[ord[1]], M[ord[2]]];
      // The rim only has to stay still. Two neighbouring hexagons sharing a
      // rim vertex can flip at the same time; blocking that starves the patch
      // right where the pointer is.
      for (let i = 0; i < 3; i++) if (vmove[n[i]] || vmove[m[i]]) return null;

      const T = [ts[ord[0]], ts[ord[1]], ts[ord[2]]];
      const trans = [], next = [];
      for (let i = 0; i < 3; i++) {
        // A tile slides by the vector from v to the one neighbour it misses.
        const away = n[(i + 2) % 3];
        trans.push(vx[away] - vx[v], vy[away] - vy[v]);
        next.push([n[(i + 2) % 3], m[(i + 2) % 3], v, m[(i + 1) % 3]]);
      }

      const dk = [0, 0, 0, 0];
      let dx = 0, dy = 0;
      for (let i = 0; i < 3; i++) {
        dx += vx[n[i]] - vx[v];
        dy += vy[n[i]] - vy[v];
        for (let j = 0; j < N; j++) dk[j] += vk[n[i] * 4 + j] - vk[v * 4 + j];
      }

      const rim = [n[0], m[0], n[1], m[1], n[2], m[2]];
      let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
      for (let i = 0; i < 6; i++) {
        const h = rim[i];
        if (vx[h] < x0) x0 = vx[h];
        if (vx[h] > x1) x1 = vx[h];
        if (vy[h] < y0) y0 = vy[h];
        if (vy[h] > y1) y1 = vy[h];
      }

      const f = {
        v: v, T: T, trans: trans, next: next, dk: dk, rim: rim,
        s: 0, born: now, nx: vx[v] + dx, ny: vy[v] + dy,
        x0: x0 - 1, y0: y0 - 1, x1: x1 + 1, y1: y1 + 1,
        old: new Float32Array(24)
      };
      for (let i = 0; i < 3; i++) {
        const o = T[i] * 4;
        for (let q = 0; q < 4; q++) {
          f.old[i * 8 + q * 2] = vx[tvert[o + q]];
          f.old[i * 8 + q * 2 + 1] = vy[tvert[o + q]];
        }
        tbusy[T[i]] = 1;
      }
      vmove[v] = 1;
      for (let i = 0; i < 6; i++) vheld[rim[i]]++;
      return f;
    }

    function commit(f, now) {
      for (let i = 0; i < 3; i++) {
        const o = f.T[i] * 4;
        for (let q = 0; q < 4; q++) {
          const c = tvert[o + q];
          if (c === f.v) continue;
          const b = vtile[c], ix = b.indexOf(f.T[i]);
          if (ix >= 0) b.splice(ix, 1);
        }
      }

      // Move the centre on the integer lattice, then rebuild its pixel
      // position from scratch rather than accumulating the displacement.
      let x = 0, y = 0;
      for (let j = 0; j < N; j++) {
        const kj = vk[f.v * 4 + j] + f.dk[j];
        vk[f.v * 4 + j] = kj;
        x += kj * DIR[j][0];
        y += kj * DIR[j][1];
      }
      vx[f.v] = ORIGIN_X + x * edge;
      vy[f.v] = ORIGIN_Y - y * edge;
      placeVert(f.v);

      for (let i = 0; i < 3; i++) {
        const t = f.T[i], o = t * 4;
        for (let q = 0; q < 4; q++) {
          tvert[o + q] = f.next[i][q];
          if (f.next[i][q] !== f.v) vtile[f.next[i][q]].push(t);
        }
        ttype[t] = typeOf(o);
        recentre(t);
        placeTile(t);
        tbusy[t] = 0;
      }

      for (let i = 0; i < 6; i++) vheld[f.rim[i]]--;
      vmove[f.v] = 0;
      vcool[f.v] = now + COOLDOWN;
    }

    function typeOf(o) {
      const a = tvert[o] * 4, b = tvert[o + 1] * 4, c = tvert[o + 2] * 4;
      let j1 = 0, j2 = 0;
      for (let j = 0; j < N; j++) {
        if (vk[b + j] !== vk[a + j]) j1 = j;
        if (vk[c + j] !== vk[b + j]) j2 = j;
      }
      const t = PAIR_OF[Math.min(j1, j2) * 4 + Math.max(j1, j2)];
      return t === undefined ? 0 : t;
    }

    /* ---- drawing -------------------------------------------------------- */

    function quad(x0, y0, x1, y1, x2, y2, x3, y3, css) {
      ctx.beginPath();
      ctx.moveTo(x0, y0); ctx.lineTo(x1, y1); ctx.lineTo(x2, y2); ctx.lineTo(x3, y3);
      ctx.closePath();
      ctx.fillStyle = css;
      ctx.fill();
      ctx.stroke();
    }

    function drawTile(i) {
      const o = i * 4;
      const a = tvert[o], b = tvert[o + 1], c = tvert[o + 2], d = tvert[o + 3];
      quad(vx[a], vy[a], vx[b], vy[b], vx[c], vy[c], vx[d], vy[d],
           fillCss[ttype[i] * BANDS + bandOf(tcy[i])]);
    }

    function drawFlip(f, ease) {
      // Underneath: the arrangement the tiles are heading for. It covers the
      // hexagon exactly, so whatever the sliding tiles uncover is a finished
      // legal tiling rather than a hole.
      for (let i = 0; i < 3; i++) {
        const q = f.next[i];
        const ax = q[0] === f.v ? f.nx : vx[q[0]], ay = q[0] === f.v ? f.ny : vy[q[0]];
        const bx = q[1] === f.v ? f.nx : vx[q[1]], by = q[1] === f.v ? f.ny : vy[q[1]];
        const cx = q[2] === f.v ? f.nx : vx[q[2]], cy = q[2] === f.v ? f.ny : vy[q[2]];
        const dx = q[3] === f.v ? f.nx : vx[q[3]], dy = q[3] === f.v ? f.ny : vy[q[3]];
        quad(ax, ay, bx, by, cx, cy, dx, dy,
             ghostCss[ttype[f.T[i]] * BANDS + bandOf((ay + by + cy + dy) / 4)]);
      }
      // On top: the three tiles themselves, sliding rigidly into place. Both
      // endpoints sit inside a convex hexagon, so they never leave it.
      for (let i = 0; i < 3; i++) {
        const mx = f.trans[i * 2] * ease, my = f.trans[i * 2 + 1] * ease;
        const o = i * 8;
        quad(f.old[o] + mx, f.old[o + 1] + my, f.old[o + 2] + mx, f.old[o + 3] + my,
             f.old[o + 4] + mx, f.old[o + 5] + my, f.old[o + 6] + mx, f.old[o + 7] + my,
             fillCss[ttype[f.T[i]] * BANDS +
                     bandOf((f.old[o + 1] + f.old[o + 3] + f.old[o + 5] + f.old[o + 7]) / 4 + my)]);
      }
    }

    function paint(x0, y0, x1, y1) {
      if (!tgrid) return;

      // Snap the repaint window to whole device pixels. On a fractional edge
      // both the erase and the clip get antialiased, and Firefox blends them
      // hard enough to leave a hairline around every rearranged hexagon.
      x0 = Math.floor(x0 * dpr) / dpr; y0 = Math.floor(y0 * dpr) / dpr;
      x1 = Math.ceil(x1 * dpr) / dpr;  y1 = Math.ceil(y1 * dpr) / dpr;

      // Clip, and only then erase and redraw. Drawing must never escape the
      // erased window: a 1px antialiased edge covers each pixel it touches
      // only partly, so redrawing it over pixels that were not cleared first
      // blends the line colour in again, and tiles straddling the window grow
      // a steadily darker outline as the window sweeps past them. Antialiased
      // edges are not idempotent.
      ctx.save();
      ctx.beginPath();
      ctx.rect(x0, y0, x1 - x0, y1 - y0);
      ctx.clip();

      ctx.fillStyle = grad;
      ctx.fillRect(x0, y0, x1 - x0, y1 - y0);
      ctx.lineWidth = 1;
      ctx.lineJoin = 'round';
      ctx.strokeStyle = lineCss;

      // Tiles are pulled in with a whole tile radius of slack, so anything
      // whose ink reaches into the window is redrawn even if its body is
      // outside it.
      const list = query(tgrid, x0, y0, x1, y1, maxR, scratch);
      for (let m = 0; m < list.length; m++) if (!tbusy[list[m]]) drawTile(list[m]);

      // Any rearrangement overlapping this window has to be redrawn too, or
      // the fill above would wipe tiles that are still mid-slide.
      for (let i = 0; i < live.length; i++) {
        const f = live[i];
        if (f.x1 < x0 || f.x0 > x1 || f.y1 < y0 || f.y0 > y1) continue;
        drawFlip(f, f.s * f.s * (3 - 2 * f.s));
      }
      ctx.restore();
    }

    /* ---- loop ----------------------------------------------------------- */

    function stir(now) {
      // Rearrangements are paid for out of pointer travel, so a pointer left
      // sitting still lets the tiling settle instead of churning under it.
      if (ptr.budget < 1 || live.length >= MAX_LIVE) return;

      const cand = query(vgrid, ptr.x - influence, ptr.y - influence,
                                ptr.x + influence, ptr.y + influence, 0, vscratch);
      pool.length = 0;
      const r2 = influence * influence;
      for (let i = 0; i < cand.length; i++) {
        const v = cand[i];
        if (vtile[v].length !== 3 || vcool[v] > now || vmove[v] || vheld[v]) continue;
        const dx = vx[v] - ptr.x, dy = vy[v] - ptr.y;
        if (dx * dx + dy * dy > r2) continue;
        pool.push(v);
      }

      let guard = 0;
      while (ptr.budget >= 1 && live.length < MAX_LIVE && pool.length && guard++ < 30) {
        // Nearest of three random draws. Sampling the whole radius uniformly
        // scatters the work across it; this pulls it in under the pointer
        // while still leaving the choice unpredictable.
        let best = -1, bestIx = -1, bestD = Infinity;
        for (let k = 0; k < 3; k++) {
          const ix = (Math.random() * pool.length) | 0;
          const v = pool[ix];
          const dx = vx[v] - ptr.x, dy = vy[v] - ptr.y;
          const d = dx * dx + dy * dy;
          if (d < bestD) { bestD = d; best = v; bestIx = ix; }
        }
        pool.splice(bestIx, 1);
        // A site can still be blocked by a neighbouring flip holding its rim.
        // That costs nothing; only a rearrangement that actually starts is
        // charged, so a blocked patch doesn't silently swallow the budget.
        const f = plan(best, now);
        if (f) { live.push(f); ptr.budget -= 1; }
      }
    }

    function frame(now) {
      if (ptr.on) stir(now);

      // One repaint window per frame, not one per rearrangement. They cluster
      // around the pointer and overlap heavily, so painting each separately
      // redraws the same neighbours several times over. The union is bounded
      // by the pointer radius either way.
      let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity, dirty = false;
      for (let i = live.length - 1; i >= 0; i--) {
        const f = live[i];
        f.s = Math.min(1, (now - f.born) / flipMs);
        if (f.x0 < x0) x0 = f.x0;
        if (f.y0 < y0) y0 = f.y0;
        if (f.x1 > x1) x1 = f.x1;
        if (f.y1 > y1) y1 = f.y1;
        dirty = true;
        // Commit before painting: a landed flip is identical to the
        // arrangement already drawn underneath it, so the handover is seamless.
        if (f.s >= 1) { commit(f, now); live.splice(i, 1); }
      }
      if (dirty) paint(x0, y0, x1, y1);

      // Nothing in flight means every nearby site was blocked. Drop the
      // unspent budget rather than spinning on it until one frees up.
      if (!live.length) { ptr.budget = 0; raf = 0; return; }
      raf = requestAnimationFrame(frame);
    }

    function wake() {
      if (raf || still.matches) return;
      raf = requestAnimationFrame(frame);
    }

    /* ---- wiring --------------------------------------------------------- */

    function resize() {
      const r = host.getBoundingClientRect();
      const w = Math.max(1, Math.round(r.width)), h = Math.max(1, Math.round(r.height));
      const d = Math.min(window.devicePixelRatio || 1, 2);
      if (w === W && h === H && d === dpr) return;
      W = w; H = h; dpr = d;
      canvas.width = Math.round(W * dpr);
      canvas.height = Math.round(H * dpr);
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      live.length = 0;
      makeGradient();
      build();
      paint(0, 0, W, H);
    }

    let lastX = 0, lastY = 0, tracking = false;
    function onMove(e) {
      const r = canvas.getBoundingClientRect();
      const x = e.clientX - r.left, y = e.clientY - r.top;
      if (tracking) ptr.budget = Math.min(ptr.budget + Math.hypot(x - lastX, y - lastY) * perPx, 5);
      lastX = x; lastY = y; tracking = true;
      ptr.x = x; ptr.y = y;
      ptr.on = x >= -influence && y >= -influence && x <= W + influence && y <= H + influence;
      if (ptr.on && ptr.budget >= 1) wake();
    }

    function onLeave() { ptr.on = false; tracking = false; ptr.budget = 0; }

    // Four times as many tiles as before means a rebuild is no longer free.
    // Coalesce resize events so dragging a window edge rebuilds once at the
    // end rather than on every intermediate width.
    let pending = 0;
    function onResize() {
      clearTimeout(pending);
      pending = setTimeout(resize, 120);
    }
    const ro = new ResizeObserver(onResize);
    ro.observe(host);
    window.addEventListener('pointermove', onMove, { passive: true });
    window.addEventListener('pointerdown', onMove, { passive: true });
    window.addEventListener('pointerleave', onLeave, { passive: true });
    window.addEventListener('blur', onLeave);

    usePalette(opts.palette || 'argent');
    resize();

    return {
      canvas: canvas,
      setPalette: function (p) { usePalette(p); paint(0, 0, W, H); },
      destroy: function () {
        cancelAnimationFrame(raf);
        clearTimeout(pending);
        ro.disconnect();
        window.removeEventListener('pointermove', onMove);
        window.removeEventListener('pointerdown', onMove);
        window.removeEventListener('pointerleave', onLeave);
        window.removeEventListener('blur', onLeave);
        canvas.remove();
      }
    };
  }

  return { mount: mount, PALETTES: PALETTES };
})();

/* ------------------------------------------------------------------ *
 * The palettes.
 *
 * Both keep the tone relationships the tiling was tuned with — faces per
 * orientation class sitting close together, `alpha` mixing each face further
 * back into the field gradient — and move them onto this site's own grounds:
 * the light field lands on --bg-base and the dark one on the top of
 * --bg-gradient. Spread the faces further apart and the tiling stops reading
 * as a ground and starts competing with the text sitting directly on it.
 *
 * `line` does two jobs, and the second one is easy to miss: its RGB is the
 * contour stroke, and the engine also mixes that same RGB 16% into every tile
 * to make the ghost — the arrangement drawn under a hexagon while its three
 * tiles slide. The ghost ignores the alpha, so a line colour far from its own
 * field flashes a patch under every rearrangement. Each one below stays near
 * its field and pays for the lost contour with alpha instead.
 * ------------------------------------------------------------------ */

var PLATE = {
    light: {
        field: ['#eef2f6', '#d9dee3'],
        rhomb: ['#e9edf2', '#e4e8ed', '#e0e4e9', '#dbdfe4'],
        square: ['#d1d5da', '#caced3'],
        alpha: 0.45,
        line: [176, 184, 193, 0]
    },
    dark: {
        field: ['#2a3138', '#191d23'],
        rhomb: ['#2f363d', '#2d343b', '#2c333a', '#2a3138'],
        square: ['#363d44', '#3b4249'],
        alpha: 0.32,
        line: [102, 109, 116, 0]
    }
};

(function () {
    var root = document.documentElement;
    var host = document.getElementById('plate');
    if (!host) return;

    /*
     * The stamp in the head is what normally answers this, and script.js keeps
     * it current afterwards. The fallbacks are for the one frame before either
     * has run — a cached page restored with the attribute missing, say — and
     * read the same key script.js writes, so all three agree.
     */
    function theme() {
        var stamped = root.getAttribute('data-theme');
        if (stamped === 'dark' || stamped === 'light') return stamped;
        try {
            var saved = window.localStorage.getItem('alganet-theme');
            if (saved === 'dark' || saved === 'light') return saved;
        } catch (e) { /* private mode, blocked site data: fall back to the system */ }
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }

    var current = theme();
    var bg = AmmannBeenker.mount(host, {
        palette: PLATE[current],
        seed: 7,
        // Pinned. Left to itself the engine steps the edge from 32 to 21 the
        // moment the smaller viewport dimension crosses 640 — a real change of
        // tile size, just one that only shows up at a single width.
        edge: 32
    });

    // The toggle and the system listener both only set data-theme; following
    // the attribute rather than either of them means there is one path here
    // instead of two doing the same work.
    new MutationObserver(function () {
        var next = theme();
        if (next === current) return;
        current = next;
        bg.setPalette(PLATE[next]);
    }).observe(root, { attributes: true, attributeFilter: ['data-theme'] });
}());
